### ISSUE TITLE
Some problems when i try to modify source code.

### ISSUE THREAD

**Issue by 444thLiao** [varapp/varapp-frontend-react#2]
Sorry for bothering you.But I meet some problems I can't fix it right now according to my knowledge.

I make scenario part into some kinds of 'filters set', when I click a filters set, I can produce several filters effect. But I need to make a change like 'when I click preset1, the following filters it have will be chosen at the same time.' 

So I follow the onchange function, I found the ACTION_UPDATE_ONE_FILTER_VALUE.
So I make it like in FilterActions.js

```
    updateOneFilterValue: function(field, value){
        //console.log("ACTION updateOneFilterValue", field, value);
        dispatcher.dispatch({
            actionType: FilterConstants.ACTION_UPDATE_ONE_FILTER_VALUE,
            field: field,
            value: value
        });
        return RestService.getVariants('demo_mini',300,'filter=genotype='+value)
            .then(function(data){
                dispatcher.dispatch({
                    actionType:FilterConstants.UPDATE_FILTERS_WITH_PANEL,
                    data:data
                })
                return data
            })
            .fail(function(err){
                console.log(err)
            })
        
    },
```

But some problems occur, it sent a GET request but fail with 0 code or 'abort' statustext. 
Never mind the arguments in getVariants , I just want to try it.

I also try using `RestService.getVariants(Api.getDb(),300,Api.buildQueryDict())`, But it will make a more weird problems 
```
Uncaught TypeError: FilterActions.fetchGlobalStats is not a function
    at AppStore.js:96

```
But I actually didn't change this file anything. So I really upset because I don't know flux a lot. please try it and give me some advise.

**Comment by jdelafon** [comment]
`Api.buildQueryDict()` is meant for the router state, not here (I admit that it should be better documented, though). `FilterCollection.buildUrlArgs` is probably what you were looking for. But it should work with plain strings in the first place, so keep your first attempt.

A 0 status for a GET request does not give much information about the error. What you can do to debug this is to copy the URL that your GET request was addressed to, then try to call it with curl (you will need to add an Authorization header with -H, something like  

    curl -H "Authorization: JWT <token>" <url>

This way, it has nothing to do with React, it just tests that the backend is correctly able to respond to your request. If it doesn't work, inspect the URL to find where it is not well formatted, or verify with other requests that the backend is properly configured.

_[Removed my last comment]_
